version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'
    restart: always
    container_name: postgres-local
    ports:
      - 5432:5432
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
     - ./resources:/docker-entrypoint-initdb.d